name: Go2

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      test:
        description: "test_input"
        default: "true"
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      env: 
        SOME_ENV: ${{ github.event.inputs.test || 'default' }}
      run:  if [ ${{ github.event.inputs.test_intput }} == "true" ]; then
            go run .
          fi
